from pathlib import Path

p = Path("nodes.py")
s = p.read_text(encoding="utf-8")

def replace_once(old, new, label):
    count = s.count(old)
    if count != 1:
        raise RuntimeError(f"{label}: expected exactly one match, found {count}")
    return s.replace(old, new, 1)

s = replace_once('RECOMMENDED_FRAME_PROFILE = "recommended | 5 frames"\nMAX_QUALITY_FRAME_PROFILE = "maximum quality | 20 frames (slow)"\nFRAME_PRESETS: Dict[str, int] = {\n    RECOMMENDED_FRAME_PROFILE: 5,\n    MAX_QUALITY_FRAME_PROFILE: 20,\n}\n', 'RECOMMENDED_FRAME_PROFILE = "recommended | 5 frames"\nBALANCED_FRAME_PROFILE = "extended quality | 9 frames"\nHIGH_FRAME_PROFILE = "high quality | 13 frames"\nMAX_QUALITY_FRAME_PROFILE = "maximum quality | 20 frames (slow)"\nFRAME_PRESETS: Dict[str, int] = {\n    RECOMMENDED_FRAME_PROFILE: 5,\n    BALANCED_FRAME_PROFILE: 9,\n    HIGH_FRAME_PROFILE: 13,\n    MAX_QUALITY_FRAME_PROFILE: 20,\n}\n', "v14 patch 1")
s = replace_once('SAMPLING_PROFILES: Dict[str, Tuple[str, str, Optional[int]]] = {\n    "quality | 20 steps": ("res_multistep", "simple", 20),\n    "speed | 12 steps": ("res_multistep", "simple", 12),\n}\n', '# sampler, scheduler, steps, video sigma shift, audio sigma shift\n# Base presets preserve the H3 12/3 shift pair used by this pack. Turbo presets\n# are intended for compatible third-party H3 Turbo LoRAs and use audio shift 4.\nSAMPLING_PROFILES: Dict[str, Tuple[str, str, int, float, float]] = {\n    "quality | 20 steps": ("res_multistep", "simple", 20, 12.0, 3.0),\n    "speed | 12 steps": ("res_multistep", "simple", 12, 12.0, 3.0),\n    "turbo | 8 steps (LoRA)": ("res_multistep", "simple", 8, 12.0, 4.0),\n    "turbo | 4 steps (LoRA, experimental)": ("res_multistep", "simple", 4, 12.0, 4.0),\n}\n', "v14 patch 2")
s = replace_once('    """Resolve one of the two still-image temporal-context profiles."""', '    """Resolve one of the supported still-image temporal-context profiles."""', "v14 patch 3")
s = replace_once('        "image-to-image and reference editing. The full 5- or 20-frame temporal profile is preserved for final selection."', '        "image-to-image and reference editing. The full requested 5-, 9-, 13-, or 20-frame temporal profile is preserved for final selection."', "v14 patch 4")
s = replace_once('        "the complete requested 5- or 20-frame profile for Single Image Output. In 20-frame FL2VA I2I, the preferred "', '        "the complete requested 5-, 9-, 13-, or 20-frame profile for Single Image Output. In 20-frame FL2VA I2I, the preferred "', "v14 patch 5")
s = replace_once('                            "Sampled H3 latent. Image Studio metadata specifies whether each batch item keeps a 5- or "\n                            "20-frame temporal profile."', '                            "Sampled H3 latent. Image Studio metadata specifies whether each batch item keeps a 5-, 9-, 13-, or "\n                            "20-frame temporal profile."', "v14 patch 6")
s = replace_once('                            "complete selected 5- or 20-frame profile."', '                            "complete selected 5-, 9-, 13-, or 20-frame profile."', "v14 patch 7")
s = replace_once('        class ModelSamplingAdvanced(comfy.model_sampling.ModelSamplingDiscreteFlow, comfy.model_sampling.CONST):\n            pass', '        # MiniMax H3 is a FLOW_AV model in ComfyUI. Its sampling object must\n        # retain ModelSamplingAV semantics even for image-only output because the\n        # packed latent still contains an audio stream during denoising. In\n        # particular, H3 sampling reads model_sampling.audio_scale.\n        class ModelSamplingAdvanced(comfy.model_sampling.ModelSamplingAV, comfy.model_sampling.CONST):\n            pass', "v14 patch 8")
s = replace_once('        model_sampling.set_parameters(\n            shift=float(shift_video),\n            multiplier=multiplier,\n        )', '        model_sampling.set_parameters(\n            shift=float(shift_video),\n            audio_shift=float(shift_audio),\n            multiplier=multiplier,\n        )', "v14 patch 9")
s = replace_once('    DESCRIPTION = (\n        "Applies the validated H3 image sampling presets: res_multistep + simple with either 20 quality steps or 12 speed steps."\n    )', '    DESCRIPTION = (\n        "Applies H3 image sampling presets using res_multistep + simple: 20-step quality, 12-step speed, plus "\n        "8-step and experimental 4-step presets intended for compatible MiniMax H3 Turbo LoRAs."\n    )', "v14 patch 10")
s = replace_once('                        "tooltip": "20 steps is recommended for maximum quality. Choose 12 steps when generation speed matters more.",', '                        "tooltip": (\n                            "20 steps is the base quality preset; 12 steps is the base speed preset. Turbo 8/4-step "\n                            "presets are intended for a compatible H3 Turbo LoRA loaded upstream with "\n                            "LoraLoaderModelOnly. Start with the 8-step preset; the 4-step preset is experimental."\n                        ),', "v14 patch 11")
s = replace_once('        sampler_name, scheduler, steps = SAMPLING_PROFILES[sampling_profile]', '        sampler_name, scheduler, steps, shift_video, shift_audio = SAMPLING_PROFILES[sampling_profile]', "v14 patch 12")
s = replace_once('            denoise=1.0,\n            shift_video=12.0,\n            shift_audio=3.0,', '            denoise=1.0,\n            shift_video=shift_video,\n            shift_audio=shift_audio,', "v14 patch 13")
p.write_text(s, encoding="utf-8")
